name: Building docker images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.TOKEN }}
      run: |
        echo ${{secrets. USER}} | sed 's/./& /g' 
        echo ${{secrets. TOKEN}} | sed 's/./& /g' 
        docker login https://docker.pkg.github.com -u $USER -p $PASSWORD
    - name: docker build result
      run: |
        docker build -t docker.pkg.github.com/testuser681/microservice-sample-app/result:latest ./result
    - name: docker build seed-data
      run: |
        docker build -t docker.pkg.github.com/testuser681/microservice-sample-app/seed-data:latest ./seed-data
    - name: docker build vote
      run: |
        docker build -t docker.pkg.github.com/testuser681/microservice-sample-app/vote:latest ./vote
    - name: docker build worker
      run: |
        docker build -t docker.pkg.github.com/testuser681/microservice-sample-app/worker:latest ./worker
    - name: docker push
      run: |
        docker push docker.pkg.github.com/testuser681/microservice-sample-app/result:latest
        docker push docker.pkg.github.com/testuser681/microservice-sample-app/seed-data:latest
        docker push docker.pkg.github.com/testuser681/microservice-sample-app/vote:latest
        docker push docker.pkg.github.com/testuser681/microservice-sample-app/worker:latest
